### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by hhboy98** [YuvalNirkin/hyperseg#6]
Thank you for your sharing.
Why do I break out CUDA out of memory every time in a fixed training stage

**Comment by vcjmhg** [comment]
@hhboy98 , I also meet this problem. Have you solved it?

**Comment by YuvalNirkin** [comment]
Try to reduce the batch size.

**Comment by vcjmhg** [comment]
ok, thank u!

**Comment by leo-hao** [comment]
Hi，a new problem has appeared again, even though I set the batch_size to 1, it still out of memory.
![image](https://user-images.githubusercontent.com/20486586/134764222-7936381d-d99f-47a4-82c0-8d9dc0dd7e75.png)

**Comment by YuvalNirkin** [comment]
It seems like your GPU does not have enough memory (10GB) for running the training even with *batch_size* set to 1. In the configuration you have attempted to run the training resolution is 1024x512 this is quite a large resolution, you can try reducing it to 512x256 and you should still get reasonable results. Alternatively you try training a smaller model, for example using the the B0 backbone instead of the B1 backbone.

**Comment by leo-hao** [comment]
Dear doctor Nirkin, I know where I am wrong, I need to modify the batch-size in /config/train/cityscapes_efficientnet_b1_hyperseg-m.py, instead of writing --batch-size 1 in the terminal.  
With the help of your tips, I finally started my training successfully. Sincerely thank you for your patience and help. Wish you a happy life and smooth work.
